"use client";
import { useMemo, useState } from "react";
type System = "price" | "sac";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
function parseMoney(v:string){const c=v.replace(/\s/g,"").replace(/R\$/gi,"");return Number(c.includes(",")?c.replace(/\./g,"").replace(",","."):c)||0}
function rateFor(p:number,pmt:number,n:number){if(pmt*n<=p)return 0;let a=0,b=1;for(let i=0;i<160;i++){const r=(a+b)/2,pv=pmt*(1-Math.pow(1+r,-n))/r;if(pv>p)a=r;else b=r}return(a+b)/2}
function pv(pmt:number,r:number,n:number){if(n<=0)return 0;return r===0?pmt*n:pmt*(1-Math.pow(1+r,-n))/r}
export default function Home(){
 const[system,setSystem]=useState<System>("price"),[principal,setPrincipal]=useState("10.000,00"),[payment,setPayment]=useState("451,81"),[total,setTotal]=useState("108"),[paid,setPaid]=useState("0"),[customQuantity,setCustomQuantity]=useState(""),[availableValue,setAvailableValue]=useState(""),[copied,setCopied]=useState(false);
 const calc=useMemo(()=>{const financed=parseMoney(principal),installment=parseMoney(payment),totalPeriods=Math.max(0,Math.floor(Number(total)||0)),paidPeriods=Math.max(0,Math.floor(Number(paid)||0)),remaining=Math.max(0,totalPeriods-paidPeriods),valid=financed>0&&installment>0&&totalPeriods>0&&paidPeriods<=totalPeriods,rate=valid&&system==="price"?rateFor(financed,installment,totalPeriods):0;
 const valueFor=(q:number)=>{if(!valid||q<=0||q>remaining)return null;if(system==="sac")return q*(financed/totalPeriods);return pv(installment,rate,remaining)-pv(installment,rate,remaining-q)};
 const half=remaining>0?Math.ceil(remaining/2):0,quantities=[1,3,5,10,half].filter((q,index,list)=>q>0&&list.indexOf(q)===index),rows=quantities.map(quantity=>({label:`${quantity} ${quantity===1?"parcela":"parcelas"}`,quantity,value:valueFor(quantity)}));
 const chosen=Math.max(0,Math.floor(Number(customQuantity)||0)),chosenValue=valueFor(chosen),budget=parseMoney(availableValue);let possible=0;for(let q=1;q<=remaining;q++){const v=valueFor(q);if(v!==null&&v<=budget+.005)possible=q;else break}const usedValue=possible?valueFor(possible):0,leftover=Math.max(0,budget-(usedValue||0));return{valid,remaining,rate,rows,chosen,chosenValue,budget,possible,usedValue,leftover}},[principal,payment,total,paid,system,customQuantity,availableValue]);
 const customLines=[calc.chosen>0?`${calc.chosen} parcelas escolhidas: ${calc.chosenValue===null?"não disponível":money.format(calc.chosenValue)}`:null,calc.budget>0?`Com ${money.format(calc.budget)}: aproximadamente ${calc.possible} ${calc.possible===1?"parcela":"parcelas"} (${money.format(calc.usedValue||0)})`:null].filter(Boolean) as string[];
 const text=calc.valid?["*ANTECIPAÇÃO*","",...calc.rows.map(x=>`${x.label}: ${x.value===null?"não disponível":money.format(x.value)}`),...(customLines.length?["","*SIMULAÇÃO PERSONALIZADA*",...customLines]:[])].join("\n"):"Preencha os dados do contrato.";
 async function copy(){await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <main><header className="topbar"><div className="brand"><span className="logo">%</span><span>Amortiza Fácil</span></div><span className="tag">Consignado</span></header>
 <section className="intro"><p className="eyebrow">SIMULAÇÃO RÁPIDA E SEGURA</p><h1>Calcule a amortização<br/>do seu contrato.</h1><p>Informe os dados abaixo e receba os valores prontos para enviar pelo WhatsApp.</p></section>
 <section className="workspace"><div className="panel"><Title n="1" title="Dados do contrato" sub="Preencha conforme consta no contrato."/><div className="switcher" role="group" aria-label="Sistema"><button className={system==="price"?"active":""} onClick={()=>setSystem("price")}>Tabela Price</button><button className={system==="sac"?"active":""} onClick={()=>setSystem("sac")}>Tabela SAC</button></div>
 <div className="fields"><MoneyField label="Valor financiado" value={principal} set={setPrincipal}/><MoneyField label="Valor da parcela" value={payment} set={setPayment}/><label>Total de parcelas<input inputMode="numeric" type="number" min="1" value={total} onChange={e=>setTotal(e.target.value)}/></label><label>Parcelas já pagas<input inputMode="numeric" type="number" min="0" value={paid} onChange={e=>setPaid(e.target.value)}/></label></div>
 {!calc.valid&&<p className="error">Confira os valores. As parcelas pagas não podem superar o total.</p>}<div className="remaining"><span>Parcelas restantes</span><strong>{calc.remaining}</strong></div><p className="hint">{system==="price"?<>Taxa mensal estimada: <strong>{calc.valid?`${(calc.rate*100).toFixed(3).replace(".",",")}% a.m.`:"—"}</strong></>:<>Na SAC, a amortização é constante e não depende da taxa.</>}</p></div>
 <div className="panel result-panel"><Title n="2" title="Valores para antecipação" sub="Estimativa das últimas parcelas."/><div className="result-list">{calc.rows.map(x=><div className="result-row" key={x.label}><span>{x.label}</span><strong>{x.value===null?"—":money.format(x.value)}</strong></div>)}</div>
 <div className="custom-box"><h3>Simulação personalizada</h3><label>Quantas parcelas deseja antecipar?<input inputMode="numeric" type="number" min="1" max={calc.remaining||undefined} placeholder="Ex.: 7" value={customQuantity} onChange={e=>setCustomQuantity(e.target.value)}/></label>{calc.chosen>0&&<div className="custom-result"><span>Valor estimado</span><strong>{calc.chosenValue===null?"Quantidade indisponível":money.format(calc.chosenValue)}</strong></div>}<div className="or"><span>ou</span></div><MoneyField label="Quanto você tem disponível?" value={availableValue} set={setAvailableValue}/>{calc.budget>0&&<div className="budget-result"><div><span>Você conseguiria antecipar</span><strong>{calc.possible} {calc.possible===1?"parcela":"parcelas"}</strong></div><p>{calc.possible>0?<>Custo estimado: <b>{money.format(calc.usedValue||0)}</b> · Sobra: <b>{money.format(calc.leftover)}</b></>:"O valor ainda não alcança a última parcela."}</p></div>}</div>
 <button className="copy" onClick={copy} disabled={!calc.valid}><span>{copied?"✓":"▣"}</span>{copied?"Copiado!":"Copiar para WhatsApp"}</button><p className="official">Valores estimados. O cálculo oficial deve ser solicitado à instituição financeira.</p></div></section>
 <section className="explanation"><h2>Como o cálculo funciona?</h2><p>Na Tabela Price, calculamos o valor presente das últimas parcelas, descontando os juros que ainda não venceram. Na SAC, usamos a amortização constante proporcional ao número de parcelas antecipadas.</p></section><footer>Amortiza Fácil · Ferramenta de simulação financeira</footer></main>}
function Title({n,title,sub}:{n:string,title:string,sub:string}){return <div className="panel-title"><span className="step">{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function MoneyField({label,value,set}:{label:string,value:string,set:(v:string)=>void}){return <label className="wide">{label}<span className="money-input"><b>R$</b><input inputMode="decimal" value={value} onChange={e=>set(e.target.value)} aria-label={label}/></span></label>}
